### ISSUE TITLE
newTimer error

### ISSUE THREAD

**Issue by liaoyinyu** [rfyiamcool/go-timewheel#8]
when I create a new timer , the following error occur:

```goroutine 52 [running]:
github.com/rfyiamcool/go-timewheel.(*TimeWheel).genUniqueID(...)
        /home/liaoyinyu/workspace/go_ws/pkg/mod/github.com/rfyiamcool/go-timewheel@v0.0.0-20200718022720-a3935e8c9b67/timer.go:468
github.com/rfyiamcool/go-timewheel.(*TimeWheel).addAny(0x0, 0xdf8475800, 0xc00029e070, 0x0, 0x0)
        /home/liaoyinyu/workspace/go_ws/pkg/mod/github.com/rfyiamcool/go-timewheel@v0.0.0-20200718022720-a3935e8c9b67/timer.go:243 +0x43
github.com/rfyiamcool/go-timewheel.(*TimeWheel).NewTimer(0x0, 0xdf8475800, 0xc000af06e8)
        /home/liaoyinyu/workspace/go_ws/pkg/mod/github.com/rfyiamcool/go-timewheel@v0.0.0-20200718022720-a3935e8c9b67/timer.go:309 +0x9d
Micor_modules/timewheel.Newtimer(...)
```
and i found the reason is the randomID of timewheel is not inittialed.
and I fixed it when create a new timewheel by 

```tw := &TimeWheel{
		// tick
		tick:      tick,
		tickQueue: make(chan time.Time, 10),
		randomID: 0,
```

and it work

**Comment by rfyiamcool** [comment]
randomID是个int64，默认就会初始化，且为零值的。

你啥哪个go版本呀？ 能提供一个例子么？
